### ISSUE TITLE
Look into open source embedding (rather than GPT)

### ISSUE THREAD

**Issue by mdr223** [mit-submit/A2rchi#103]
Cost saving measure for 801

**Comment by julius-heitkoetter** [comment]
This actually already exists, at least to a surface level. Ludo had implemented the embeddings using a model from [sentence transformers from huggingface](https://huggingface.co/sentence-transformers/all-mpnet-base-v2). You can see where to select this in the config [here](https://github.com/mit-submit/A2rchi/blob/f0d8ba790cf712f473c2a38ba8dfdb4b4e103b52/config/dev-config.yaml#L97). From I understand it worked pretty well, but not perfectly.

@ludomori99 could you elaborate on what you’ve found while experimenting with this? 

Also, if we want to use any other open source embeddings that may work better, we can swap to them pretty easily if they are on hugging face. Not sure if we think there are other models worth looking at.

Lastly, as reference I think the cost for embedding all the 801 context is between 25 and 50 cents.
