### ISSUE TITLE
Post-Mortem: Immediate Changes for Tomorrow AM

### ISSUE THREAD

**Issue by mdr223** [mit-submit/A2rchi#125]
I may be missing something(s), but I believe this will restore us to our pre-hotfix state:

1. Tear down submit06 deployment (but save conversations)
- ssh to submit06; `docker cp a2rchi-prod-801-data:conversations_test.json .` or something like that and scp back to local
- ssh to submit06; cd to `a2rchi-prod-801/deploy/prod-801/`; run `docker compose -f prod-801-compose.yaml down`
- Delete branch `temp-release-8.01` with `git push origin --delete temp-release-8.01`
- Delete branch `temp2-release-801` with `git push origin --delete temp2-release-801`

2. Move t3desk deployment back to 7683
- Remove static webpage from 7683
- Update deploy/prod-801/prod-801-compose.yaml and A2rchi/config/prod-801-config.yaml to use port 7683 and re-deploy to release-8.01 branch
    - (this will stop the deployment on 7684 and start it back on 7683)
- scp conversations from 1a. from local to t3desk and use python to merge submit06 convos with t3desk convos (probably write to a new json file, check that it looks good, and then replace)

**Comment by julius-heitkoetter** [comment]
Step 2 taken care of by action 17, caused by PR #128. Additonally, static webpage has been taken down.

**Comment by julius-heitkoetter** [comment]
Step 1 is taken care of

**Comment by julius-heitkoetter** [comment]
Json file contents have been copied, issue is revoled. 

You can find backups of the conversations here `/work/submit/juliush/a2rchi_downtime_app` and also find the code use to merge the conversation files here `/work/submit/juliush/a2rchi_downtime_app/merge_backups`. It's maybe more complicated than it needs to be, but I just wanted to double check that everything is running well with the merge.

I also tested the 8.01 deployment and can verify it is working smoothly.
