### ISSUE TITLE
Make failures in docker containers lead to visible deployment errors

### ISSUE THREAD

**Issue by julius-heitkoetter** [mit-submit/A2rchi#78]
Change code so that if one of the services crashes, then the entire github deployment reports an error. This will allow us to easily see when one of the services crashes.

**Comment by mdr223** [comment]
I think we can close this now that we have removed all background threads from our PR to simplify services (#119). Services will output an error message in the logs and the container will be killed. The container will then restart, but we will see that it is in the "restarted (n)" state.
